### PR TITLE
chore: benchmark read_json functions

### PR DESCRIPTION
**Pull request by tychoish**
Here's the run of thos code (on my laptop,) I didn't run more tests
because of runtime concerns.

I would also want to see how it coped with globs, and the way that
impacts schema inference and runtime. I also think that the structure
of the test (e.g. running the "table scan") may be a better exercise
of the network handling and less of the table function code.

My general gloss of these are:

- `read_json` is performs better (speed and consistency) than
  `read_ndjson` as the number of columns increases. (second result.)

- `read_ndjson` has marginally better best-case performance _some_,
  but not all of the time, but much more variablity overall, and
  slower worst-case performance in many situations.

- the fact that the larger tests did _not_ run multiple iterations is
  a conern, and so there are settings to tweak there.

- `read_json`'s performance is not inconsistent with `read_ndjson`.

But these results are really rough. Things to add/modify:
- glob tests
- maybe test this with the bindings
- run on better/quieter hardware
- simplify the assertion
- enforce at least 10 iterations of each test.

```
------------------------------------------------------------------------------------------------------- benchmark: 8 tests ------------------------------------------------------------------------------------------------------
Name (time in ms)                                  Min                    Max                   Mean                StdDev                 Median                   IQR            Outliers     OPS            Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_json_function[10-10-read_json]           120.2667 (1.05)        181.0317 (1.12)        143.7099 (1.06)        22.4363 (1.37)        142.1496 (1.06)        31.4659 (1.29)          4;0  6.9585 (0.94)         10         100
test_json_function[10-10-read_ndjson]         114.0293 (1.0)         161.9013 (1.0)         135.3398 (1.0)         16.3675 (1.0)         133.9657 (1.0)         24.2989 (1.0)           3;0  7.3888 (1.0)          10         100

test_json_function[100-10-read_json]        2,613.2126 (22.92)     3,841.7003 (23.73)     3,016.6098 (22.29)      407.8344 (24.92)     2,938.2436 (21.93)      545.6186 (22.45)         2;0  0.3315 (0.04)         10           2
test_json_function[100-10-read_ndjson]      2,740.0141 (24.03)    16,061.6302 (99.21)     4,999.4874 (36.94)    4,321.6125 (264.04)    3,160.7918 (23.59)    1,304.8888 (53.70)         1;2  0.2000 (0.03)         10           2

test_json_function[10-100-read_json]        2,835.7443 (24.87)    10,138.0955 (62.62)     4,620.3587 (34.14)    2,788.5390 (170.37)    2,968.1921 (22.16)    4,669.3484 (192.16)        3;0  0.2164 (0.03)         10           2
test_json_function[10-100-read_ndjson]      2,508.3037 (22.00)    10,855.2284 (67.05)     3,928.2108 (29.02)    2,520.6930 (154.01)    3,032.9019 (22.64)    1,492.8058 (61.43)         1;1  0.2546 (0.03)         10           2

test_json_function[10-250-read_json]       17,408.6613 (152.67)   18,249.8782 (112.72)   17,945.2774 (132.59)     273.0555 (16.68)    18,008.2394 (134.42)     421.2743 (17.34)         2;0  0.0557 (0.01)         10           1
test_json_function[10-250-read_ndjson]     15,616.4957 (136.95)   40,721.0071 (251.52)   20,565.2852 (151.95)   9,453.7324 (577.59)   16,165.7277 (120.67)     827.5815 (34.06)         2;2  0.0486 (0.01)         10           1
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

My ultimate goal is to understand the performance and operational
characteristics well enough to have `.json` extension (and format
specification for object store tables) to dispatch to `read_json`
rather than `read_ndjson`, because I'm pretty sure this would be more
expected semantics.

### CODE REVIEW

**Comment by tychoish** [comment]
Here's another set of results, this time running `select count(*) from read_[...]()` rather than `select *`: reading the results across in the client were, lead more variability in execution time. 

```
--------------------------------------------------------------------------------------------------- benchmark: 8 tests ---------------------------------------------------------------------------------------------------
Name (time in ms)                                 Min                   Max                  Mean              StdDev                Median                 IQR            Outliers      OPS            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_json_function[10-10-read_json]           57.2330 (1.12)        68.9685 (1.0)         65.3633 (1.02)       3.1564 (1.0)         65.5660 (1.01)       1.6986 (1.0)           2;1  15.2991 (0.98)         10         100
test_json_function[10-10-read_ndjson]         50.9679 (1.0)         69.0648 (1.00)        64.1831 (1.0)        5.0672 (1.61)        64.7978 (1.0)        3.0014 (1.77)          1;1  15.5804 (1.0)          10         100

test_json_function[10-100-read_json]         269.6489 (5.29)       334.9173 (4.86)       301.5960 (4.70)      20.7763 (6.58)       304.9123 (4.71)      30.8781 (18.18)         4;0   3.3157 (0.21)         10          19
test_json_function[10-100-read_ndjson]       287.5479 (5.64)       367.1946 (5.32)       310.5955 (4.84)      28.4226 (9.00)       299.4714 (4.62)      28.7846 (16.95)         2;1   3.2196 (0.21)         10          19

test_json_function[100-10-read_json]         282.6315 (5.55)       404.5924 (5.87)       330.9813 (5.16)      41.8461 (13.26)      320.4213 (4.94)      67.5470 (39.77)         4;0   3.0213 (0.19)         10          19
test_json_function[100-10-read_ndjson]       290.5274 (5.70)       385.4257 (5.59)       322.7534 (5.03)      26.8845 (8.52)       321.0590 (4.95)      27.7212 (16.32)         3;1   3.0983 (0.20)         10          19

test_json_function[10-250-read_json]       1,370.2310 (26.88)    2,176.5386 (31.56)    1,566.5725 (24.41)    276.4330 (87.58)    1,449.4590 (22.37)    182.0448 (107.17)        2;2   0.6383 (0.04)         10          10
test_json_function[10-250-read_ndjson]     1,400.6722 (27.48)    1,676.9972 (24.32)    1,530.6666 (23.85)     87.4726 (27.71)    1,526.4886 (23.56)     75.6628 (44.54)         4;2   0.6533 (0.04)         10          10
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by tychoish** [comment]
I ran a bunch of tests with different sized cases, all single file,
with different numbers of colums and rows.

In cases with smaller numbers of columns, `read_json` is consistently
a little faster. With larger number of columns, `read_json` is
slightly faster in the best case (min) a bit slower in the worst
case. `read_json` is slightly less consistnet (e.g. wider stddev) in
most cases.

```
---------------------------------------------------------------------------------------------------------- benchmark: 12 tests ----------------------------------------------------------------------------------------------------------
Name (time in ms)                                      Min                     Max                    Mean                StdDev                  Median                   IQR            Outliers      OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_json_function[c10.r10-read_json]              64.8999 (1.0)           70.4333 (1.0)           66.9596 (1.0)          1.7320 (1.0)           66.1494 (1.0)          1.7677 (1.0)           3;1  14.9344 (1.0)          10         100
test_json_function[c10.r10-read_ndjson]            66.7664 (1.03)          72.1683 (1.02)          68.6398 (1.03)         1.8649 (1.08)          68.3145 (1.03)         2.8946 (1.64)          3;0  14.5688 (0.98)         10         100

test_json_function[c100.r10-read_json]            252.9917 (3.90)         601.3324 (8.54)         364.2313 (5.44)       119.8445 (69.19)        303.0016 (4.58)       186.3504 (105.42)        2;0   2.7455 (0.18)         10          10
test_json_function[c100.r10-read_ndjson]          267.3375 (4.12)         561.0015 (7.97)         344.8985 (5.15)       105.0383 (60.64)        278.6691 (4.21)       167.3090 (94.65)         2;0   2.8994 (0.19)         10          10

test_json_function[c10.r100-read_json]            257.6549 (3.97)         666.9935 (9.47)         404.7339 (6.04)       151.3582 (87.39)        331.3464 (5.01)       263.3300 (148.97)        2;0   2.4708 (0.17)         10          10
test_json_function[c10.r100-read_ndjson]          271.6629 (4.19)         603.3249 (8.57)         402.1978 (6.01)       116.4815 (67.25)        391.8329 (5.92)       183.0305 (103.54)        5;0   2.4863 (0.17)         10          10

test_json_function[c100.r100-read_json]        20,482.9167 (315.61)    35,016.3200 (497.16)    23,750.9544 (354.71)   5,378.8854 (>1000.0)   21,134.3577 (319.49)   1,811.0655 (>1000.0)       2;2   0.0421 (0.00)         10           1
test_json_function[c100.r100-read_ndjson]      20,929.7424 (322.49)    29,190.0799 (414.44)    23,131.9357 (345.46)   2,949.6303 (>1000.0)   21,658.2570 (327.41)   5,021.4700 (>1000.0)       3;0   0.0432 (0.00)         10           1

test_json_function[c50.r250-read_json]         31,290.8474 (482.14)    53,452.7553 (758.91)    37,295.3891 (556.98)   8,511.1800 (>1000.0)   32,470.7198 (490.87)   7,887.3517 (>1000.0)       2;2   0.0268 (0.00)         10           1
test_json_function[c50.r250-read_ndjson]       32,036.6137 (493.63)    44,196.6619 (627.50)    35,111.3103 (524.37)   4,025.2804 (>1000.0)   33,141.5988 (501.01)   5,973.4796 (>1000.0)       1;0   0.0285 (0.00)         10           1

test_json_function[c50.r500-read_json]        131,776.0451 (>1000.0)  154,366.0370 (>1000.0)  136,896.1023 (>1000.0)  6,496.0626 (>1000.0)  134,666.4556 (>1000.0)  4,699.9490 (>1000.0)       1;1   0.0073 (0.00)         10           1
test_json_function[c50.r500-read_ndjson]      132,276.1563 (>1000.0)  138,203.4983 (>1000.0)  134,325.6237 (>1000.0)  1,592.6581 (919.53)   134,215.0530 (>1000.0)  1,228.0981 (694.76)        2;1   0.0074 (0.00)         10           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

This is a test that I want to run more of: I wrote a number of files
(the `n` in the name) to a directory and ran the same test as above
but with a path that had a glob in it. (e.g. `./path/to/glob/*.json`).
In the terminology of the above tests these are `c16.r512` files. In
this case `read_json` does a lot better.

```
--------------------------------------------------------------------------------------------- benchmark: 2 tests --------------------------------------------------------------------------------------------
Name (time in s)                                 Min                Max               Mean             StdDev             Median                IQR            Outliers     OPS            Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_json_function[glob.n16-read_json]       23.0949 (1.0)      34.8193 (1.0)      27.9614 (1.0)       6.2018 (1.0)      23.8634 (1.0)      11.4244 (1.0)           2;0  0.0358 (1.0)           5           1
test_json_function[glob.n16-read_ndjson]     53.9684 (2.34)     78.6294 (2.26)     62.3808 (2.23)     11.7704 (1.90)     54.0212 (2.26)     19.1282 (1.67)          1;0  0.0160 (0.45)          5           1
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

I've changed the sizes of the tests in the latest push, but the latest commits (aside from different numbers) from these results.

**Comment by tychoish** [comment]
These results seem broadly consistent with the ones above. The globs
are interesting, again the `n` is the number of files, and each of the
files have 16 columns and 512 entries. The results of the largest glob
test are a bit confusing, particularly the low standard deviation.

```
---------------------------------------------------------------------------------------------------------- benchmark: 18 tests -----------------------------------------------------------------------------------------------------------
Name (time in ms)                                      Min                     Max                    Mean                 StdDev                  Median                    IQR            Outliers     OPS            Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_json_function[c16.r64-read_json]             386.5620 (1.41)         984.9955 (1.0)          509.6489 (1.11)        265.7840 (1.0)          390.0599 (1.41)        159.6927 (1.0)           1;1  1.9621 (0.90)          5           1
test_json_function[c16.r64-read_ndjson]           273.2725 (1.0)        1,183.3442 (1.20)         459.9591 (1.0)         404.4355 (1.52)         276.6123 (1.0)         237.5583 (1.49)          1;1  2.1741 (1.0)           5           1

test_json_function[c32.r64-read_json]             833.0519 (3.05)       2,306.1538 (2.34)       1,349.7065 (2.93)        702.4916 (2.64)         869.6043 (3.14)      1,162.6697 (7.28)          1;0  0.7409 (0.34)          5           1
test_json_function[c32.r64-read_ndjson]           863.1807 (3.16)       2,519.7824 (2.56)       1,199.9486 (2.61)        737.8286 (2.78)         873.1659 (3.16)        421.6381 (2.64)          1;1  0.8334 (0.38)          5           1

test_json_function[c16.r256-read_json]          3,320.9077 (12.15)      6,499.5846 (6.60)       4,588.3453 (9.98)      1,707.2896 (6.42)       3,374.2007 (12.20)     3,109.5647 (19.47)         2;0  0.2179 (0.10)          5           1
test_json_function[c16.r256-read_ndjson]        3,246.6679 (11.88)      9,955.7563 (10.11)      4,661.1508 (10.13)     2,960.5884 (11.14)      3,346.8050 (12.10)     1,769.8309 (11.08)         1;1  0.2145 (0.10)          5           1

test_json_function[c32.r256-read_json]         13,098.3491 (47.93)     21,695.7197 (22.03)     16,624.9610 (36.14)     4,404.3041 (16.57)     13,675.9637 (49.44)     7,935.3976 (49.69)         2;0  0.0602 (0.03)          5           1
test_json_function[c32.r256-read_ndjson]       13,293.3491 (48.65)     20,493.3835 (20.81)     14,953.3355 (32.51)     3,107.4013 (11.69)     13,773.1758 (49.79)     2,194.8427 (13.74)         1;1  0.0669 (0.03)          5           1

test_json_function[c16.r512-read_json]         13,711.1950 (50.17)     19,959.1426 (20.26)     15,179.6592 (33.00)     2,679.4519 (10.08)     14,152.7037 (51.16)     1,810.4837 (11.34)         1;1  0.0659 (0.03)          5           1
test_json_function[c16.r512-read_ndjson]       13,410.0790 (49.07)     25,366.5440 (25.75)     17,302.4575 (37.62)     5,267.3748 (19.82)     13,948.8734 (50.43)     7,639.0752 (47.84)         1;0  0.0578 (0.03)          5           1

test_json_function[c32.r512-read_json]         56,352.4010 (206.21)    80,269.6205 (81.49)     65,738.2881 (142.92)    9,630.5371 (36.23)     64,888.2609 (234.58)   14,316.5681 (89.65)         1;0  0.0152 (0.01)          5           1
test_json_function[c32.r512-read_ndjson]       53,336.5890 (195.18)   110,496.9520 (112.18)    85,354.0955 (185.57)   28,810.2293 (108.40)    97,216.4262 (351.45)   55,501.6171 (347.55)        2;0  0.0117 (0.01)          5           1

test_json_function[glob.n16-read_json]         23,729.7327 (86.84)     33,457.0926 (33.97)     29,509.8593 (64.16)     4,873.8510 (18.34)     32,821.0365 (118.65)    8,613.8261 (53.94)         1;0  0.0339 (0.02)          5           1
test_json_function[glob.n16-read_ndjson]       53,261.7091 (194.90)    77,167.6992 (78.34)     58,226.7824 (126.59)   10,589.5984 (39.84)     53,571.8820 (193.67)    6,188.6484 (38.75)         1;1  0.0172 (0.01)          5           1

test_json_function[glob.n64-read_json]         53,052.7763 (194.14)    54,174.0053 (55.00)     53,503.9969 (116.32)      518.1465 (1.95)      53,266.4707 (192.57)      920.9298 (5.77)          1;0  0.0187 (0.01)          5           1
test_json_function[glob.n64-read_ndjson]       52,586.2974 (192.43)    54,621.0741 (55.45)     53,898.7343 (117.18)      774.4516 (2.91)      54,157.4332 (195.79)      701.3670 (4.39)          1;0  0.0186 (0.01)          5           1

test_json_function[glob.n256-read_json]       174,743.6203 (639.45)   185,830.6255 (188.66)   179,441.6750 (390.13)    4,495.2338 (16.91)    180,458.4833 (652.39)    6,630.9178 (41.52)         2;0  0.0056 (0.00)          5           1
test_json_function[glob.n256-read_ndjson]      54,289.8115 (198.67)   135,733.9736 (137.80)    89,395.1462 (194.35)   34,954.8567 (131.52)    98,121.6918 (354.73)   57,595.2347 (360.66)        2;0  0.0112 (0.01)          5           1
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by tychoish** [comment]
Here's another batch, of results. Similar pattern: `read_json` is
marginally faster in the best cases, a touch slower in the worst
cases, with greater variability. I think a lot of the specific numbers
are probably at least partially due to the test machine (my laptop)

One thing I realized while running this batch is that the column names
and types were all random, which means that (probably) the record
batches were mostly null or empty rows. I've rewritten the tests to be
more stable, and will run after my meetings this morning.

```
---------------------------------------------------------------------------------------------- benchmark: 16 tests -----------------------------------------------------------------------------------------------
Name (time in s)                                   Min                 Max                Mean             StdDev              Median                IQR            Outliers     OPS            Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_json_function[c16.r256-read_json]          3.3207 (1.0)        3.4618 (1.0)        3.3975 (1.0)       0.0612 (1.0)        3.3770 (1.0)       0.1024 (1.0)           3;0  0.2943 (1.0)           5           1
test_json_function[c16.r256-read_ndjson]        3.3585 (1.01)       7.4515 (2.15)       4.2426 (1.25)      1.7946 (29.30)      3.4534 (1.02)      1.0708 (10.46)         1;1  0.2357 (0.80)          5           1

test_json_function[c16.r512-read_json]         13.8791 (4.18)      14.4485 (4.17)      14.2182 (4.18)      0.2153 (3.52)      14.2642 (4.22)      0.2650 (2.59)          2;0  0.0703 (0.24)          5           1
test_json_function[c16.r512-read_ndjson]       13.2198 (3.98)      33.5832 (9.70)      17.7573 (5.23)      8.8552 (144.59)    13.8765 (4.11)      5.4411 (53.13)         1;1  0.0563 (0.19)          5           1

test_json_function[c32.r256-read_json]         13.3055 (4.01)      20.1305 (5.82)      15.2143 (4.48)      2.8003 (45.72)     13.9989 (4.15)      2.4341 (23.77)         1;1  0.0657 (0.22)          5           1
test_json_function[c32.r256-read_ndjson]       13.6733 (4.12)      15.6700 (4.53)      14.2500 (4.19)      0.8048 (13.14)     13.9867 (4.14)      0.5691 (5.56)          1;1  0.0702 (0.24)          5           1

test_json_function[c32.r512-read_json]         54.8734 (16.52)    102.1579 (29.51)     66.4605 (19.56)    20.1049 (328.28)    59.9354 (17.75)    15.3498 (149.88)        1;1  0.0150 (0.05)          5           1
test_json_function[c32.r512-read_ndjson]       55.1696 (16.61)     56.0198 (16.18)     55.5719 (16.36)     0.3116 (5.09)      55.5733 (16.46)     0.3798 (3.71)          2;0  0.0180 (0.06)          5           1

test_json_function[glob.n16-read_json]         21.6315 (6.51)      93.2889 (26.95)     38.5369 (11.34)    30.8401 (503.56)    23.3605 (6.92)     24.0599 (234.93)        1;1  0.0259 (0.09)          5           1
test_json_function[glob.n16-read_ndjson]       53.2634 (16.04)     97.8980 (28.28)     62.5224 (18.40)    19.7789 (322.95)    53.8182 (15.94)    11.7371 (114.61)        1;1  0.0160 (0.05)          5           1

test_json_function[glob.n64-read_json]         52.5273 (15.82)     67.1726 (19.40)     57.4066 (16.90)     5.8217 (95.06)     55.5524 (16.45)     6.7260 (65.68)         1;0  0.0174 (0.06)          5           1
test_json_function[glob.n64-read_ndjson]       55.1487 (16.61)     64.7792 (18.71)     59.5610 (17.53)     4.0897 (66.78)     59.7729 (17.70)     7.1084 (69.41)         2;0  0.0168 (0.06)          5           1

test_json_function[glob.n256-read_json]       189.8717 (57.18)    204.3920 (59.04)    197.5995 (58.16)     5.9841 (97.71)    199.2599 (59.01)     9.8475 (96.16)         2;0  0.0051 (0.02)          5           1
test_json_function[glob.n256-read_ndjson]      65.5404 (19.74)     74.5498 (21.54)     68.5133 (20.17)     3.5726 (58.33)     68.0762 (20.16)     3.8017 (37.12)         1;0  0.0146 (0.05)          5           1

test_json_function[glob.n512-read_ndjson]      60.4377 (18.20)     66.5544 (19.23)     64.3496 (18.94)     2.5286 (41.29)     65.3684 (19.36)     3.6865 (36.00)         1;0  0.0155 (0.05)          5           1
test_json_function[glob.n512-read_json]       348.8928 (105.07)   354.7129 (102.47)   351.8323 (103.56)    2.0936 (34.19)    351.9920 (104.23)    2.2518 (21.99)         2;0  0.0028 (0.01)          5           1
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by tychoish** [comment]
Here's a mini run with the more regular types and column
names. Interestingly, more stable and closer performance for both:

```
-------------------------------------------------------------------------------------------- benchmark: 6 tests -------------------------------------------------------------------------------------------
Name (time in s)                                 Min                Max               Mean            StdDev             Median               IQR            Outliers     OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_json_function[c16.r256-read_json]        3.3856 (1.03)      5.1647 (1.48)      3.9857 (1.18)     0.8143 (8.57)      3.4711 (1.02)     1.2903 (7.38)          1;0  0.2509 (0.85)          5           1
test_json_function[c16.r256-read_ndjson]      3.2833 (1.0)       3.4933 (1.0)       3.3799 (1.0)      0.0950 (1.0)       3.3932 (1.0)      0.1749 (1.0)           3;0  0.2959 (1.0)           5           1

test_json_function[c16.r512-read_json]       13.5774 (4.14)     14.1061 (4.04)     13.8168 (4.09)     0.2288 (2.41)     13.6969 (4.04)     0.3729 (2.13)          2;0  0.0724 (0.24)          5           1
test_json_function[c16.r512-read_ndjson]     13.7332 (4.18)     14.0333 (4.02)     13.9233 (4.12)     0.1241 (1.31)     13.9466 (4.11)     0.1874 (1.07)          1;0  0.0718 (0.24)          5           1

test_json_function[glob.n16-read_json]       18.2488 (5.56)     19.8288 (5.68)     18.7903 (5.56)     0.6130 (6.45)     18.5715 (5.47)     0.6186 (3.54)          1;0  0.0532 (0.18)          5           1
test_json_function[glob.n16-read_ndjson]     14.5588 (4.43)     15.3817 (4.40)     14.8998 (4.41)     0.3395 (3.57)     14.9126 (4.39)     0.5421 (3.10)          2;0  0.0671 (0.23)          5           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Review by scsmithr — APPROVED** [review]

**Pull request merged**
