### PR TITLE
fix: Infer and scan BSON files from file path

### LINKED ISSUE #2409: Cannot read bson files from location
## Description

```
> select * from 'abc.bson';
Error: Error during planning: unable to infer how to handle file extension: bson
```

### PR DESCRIPTION
**Pull request by vrongmeal**
Fixes #2409

### CODE REVIEW

**Comment by tychoish** [comment]
can you add a test case to the pytest?

**Comment by greyscaled** [comment]
I'd be down for a point release once these fixes go in

**Comment by vrongmeal** [comment]
Added test case.

**Comment by scsmithr** [comment]
```
=========================== short test summary info ============================
FAILED tests/tests/test_bson.py::test_read_bson - psycopg2.errors.InternalError_: Error during planning: unable to infer how to handle file extension: bson
========================= 1 failed, 7 passed in 3.90s ==========================
```

Binary not being rebuilt?

**Comment by tychoish** [comment]
> Binary not being rebuilt?

yeah, the cache is apparently by cargo.lock hash not the current run... 

slt-in-main fixes this.

**Review by tychoish — COMMENTED** [review]
link #2409

**Review by tychoish — APPROVED** [review]

**Comment by tychoish** [comment]
The build problem should be resolved by the ci changes in #2401

**Pull request merged**
