### PR TITLE
fix: regression in open cmd

### LINKED ISSUE #2087: \open command fails if it doesn't exist
## Description

```
> \open ./test
Error: No such file or directory (os error 2)
```

### PR DESCRIPTION
**Pull request by universalmind303**
closes #2087

### CODE REVIEW

**Comment by scsmithr** [comment]
I'm running this:

```
% cargo run --bin glaredb
    Finished dev [unoptimized + debuginfo] target(s) in 0.72s
     Running `target/debug/glaredb`
GlareDB (v0.6.1)
Type \help for help.
> \open hello
> create table hi as select 1 as a;
Table created
> 
```

And I'm getting a `databases` folder created outside of `hello`

**Comment by universalmind303** [comment]
> I'm running this:
> 
> ```
> % cargo run --bin glaredb
>     Finished dev [unoptimized + debuginfo] target(s) in 0.72s
>      Running `target/debug/glaredb`
> GlareDB (v0.6.1)
> Type \help for help.
> > \open hello
> > create table hi as select 1 as a;
> Table created
> > 
> ```
> 
> And I'm getting a `databases` folder created outside of `hello`

hmm that is weird. Taking a look now.

**Comment by universalmind303** [comment]
@scsmithr this seems to be unrelated to the regression in `\open`. I'll open up a separate issue for this & start looking into it. It seems our `NativeTableStorage` isn't properly handling the directory specified by `\open`.

**Review by tychoish — APPROVED** [review]
should we create a regression test? o

**Comment by universalmind303** [comment]
@scsmithr you were right after all. The issues were somewhat related. we were using `from_file_path` instead of `from_directory_path` when constructing the URL. This caused the prefix to get dropped later in `NativeTableStorage`.

**Pull request merged**
